// sign-up
POST http://localhost:4567/api/signup HTTP/1.1
Content-Type: application/json

{
    "username": "ducphong2",
    "password": "hello1"
}

###

// authenticate
POST http://localhost:4567/api/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "ducphong2",
    "password": "hello1"
}

###

// ListUsers
GET  http://localhost:4567/api/users?_limit=2&_page=2

###

// findUserByName
GET  http://localhost:4567/api/user/ducphong1

###

// findListUsersByName
GET  http://localhost:4567/api/users/ducphong1

###

// createNewQuestion
POST   http://localhost:4567/api/questions HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzczMTQ0ODgsImV4cCI6MTYzNzkxOTI4OH0._rnLNRU-xeP30A0Ed336R24s4RZ0bCRGvVZeleR7h6s

{
    "title": "Javascript 2",
    "text": "Loremaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 
    "tags": ["python"]
}

###

// getListQuestion
GET  http://localhost:4567/api/questions?

###

// getListQuestionByTitle
GET  http://localhost:4567/api/questions/a

###

// getQuestion
GET  http://localhost:4567/api/question/618d8b9db130eab3eb82c17f

###

// getQuestionByUser
GET  http://localhost:4567/api/question/user/ducphong2 HTTP/1.1
Content-Type: application/json

{
    "tags": ["html"]
}

###

// getQuestionByTags
GET  http://localhost:4567/api/questions/tags? HTTP/1.1
Content-Type: application/json

{
    "tags": ["python"]
}

###

// deleteQuestion
DELETE   http://localhost:4567/api/question/618d8b9db130eab3eb82c17f



###

// getQuestionByUserName
GET  http://localhost:4567/api/question/user/ducphong2


###

// createNewAnswer
POST   http://localhost:4567/api/answer/618d8b9db130eab3eb82c17f HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA

{
    "text": "Loremaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadasdadasdasdasdasdadsa"
}

###

// deleteAnswer
DELETE    http://localhost:4567/api/answer/618d8b9db130eab3eb82c17f/618e8667e9050d9186ccd824 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA

###

// getListTags
GET  http://localhost:4567/api/tags?_limit=2

###

// getListPopularTags
GET  http://localhost:4567/api/tags/populartags?

###

// searchTags
GET  http://localhost:4567/api/tags/css


###

// comment
POST   http://localhost:4567/api/comment/618d8b9db130eab3eb82c17f HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA

{
    "body": "Loremaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadasdadasdasdasdasdadsa"
}


###

// comment
POST   http://localhost:4567/api/comment/618d8b9db130eab3eb82c17f/618e8667e9050d9186ccd824 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA

{
    "body": "Loremaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadasdadasdasdasdasdadsa"
}

###

// deleteCommentForQuestion
DELETE    http://localhost:4567/api/comment/618d8b9db130eab3eb82c17f/618fadc7cedab9a446ee10df HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA


###

// deleteCommentForAnswer
DELETE    http://localhost:4567/api/comment/618d8b9db130eab3eb82c17f/618e8667e9050d9186ccd824/618fb3e674cd77b15a32e6e8 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA

###

// upVoteForQuestion
GET  http://localhost:4567/api/votes/upvote/618d8b9db130eab3eb82c17f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA
###

// downVoteQuestion
GET  http://localhost:4567/api/votes/downvote/618d8b9db130eab3eb82c17f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA
###

// unVoteQuestion
GET  http://localhost:4567/api/votes/unvote/618d8b9db130eab3eb82c17f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA

###

// upVoteForAnswer
GET  http://localhost:4567/api/votes/upvote/618d8b9db130eab3eb82c17f/618e8667e9050d9186ccd824
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA
###

// downVoteAnswer
GET  http://localhost:4567/api/votes/downvote/618d8b9db130eab3eb82c17f/618e8667e9050d9186ccd824
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA
###

// unVoteAnswer
GET  http://localhost:4567/api/votes/unvote/618d8b9db130eab3eb82c17f/618e8667e9050d9186ccd824
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGUzMTM5ZWYzOTMzMTYyZmIxMmQ1ZiIsInVzZXJuYW1lIjoiZHVjcGhvbmcyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzY3MDg5MjksImV4cCI6MTYzNzMxMzcyOX0.-efmr9VtswIFjcL8duR_jZ39eXxAbyfiQm4rs-K4CwA